// client-angular/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';

import { environment } from '../../environments/environment';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  public client = '';
  public env = '';
  constructor() {
    this.client = environment.JS_BOX_CLIENT.charAt(0).toUpperCase() + environment.JS_BOX_CLIENT.substring(1)
    this.env = environment.JS_BOX_ENVIRONMENT;
  }

  ngOnInit() { }

}

<header class="navbar navbar-expand">
  <a class="navbar-brand" [routerLink]="['/']">
    <img id="logo" height="75px" src="assets/img/JS-box.svg" alt="JS Box logo"/>
    <span class="title">JS Box {{client}} - {{env}}</span>
  </a>
</header>

// client-react/src/components/Header.js
import React from 'react'

class App extends React.Component {
  constructor () {
    super()
    this.client = process.env.REACT_APP_CLIENT.charAt(0).toUpperCase() + process.env.REACT_APP_CLIENT.substring(1)
    this.environment = process.env.REACT_APP_ENVIRONMENT
  }
  render () {
    return (
      <header className="navbar navbar-expand">
        <a className="navbar-brand" href="/">
          <img id="logo" height="75px" src="/img/JS-box.svg" alt="JS Box logo" />
          <span className="title">JS Box {this.client} - {this.environment}</span>
        </a>
      </header>
    )
  }
}

export default App
