// client-vue/src/components/ListRow.vue
<template>
  <div class="list-group-item">
    <button
      v-bind:id="item._id"
      class="btn btn-delete btn-danger bmd-btn-fab bmd-btn-fab-sm"
      value="Delete"
      v-on:click="onDelete"
    >
      &times;
    </button>
    <span
      v-bind:id="item._id"
      class="lead item-description"
      v-on:click="onUpdate"
    >
      {{item.desc}}
    </span>
  </div>
</template>

<script>
export default {
  name: 'ListRow',
  props: {
    item: Object,
    onDelete: Function,
    onUpdate: Function
  }
}
</script>

// client-react/src/components/ListRow.js
import React from 'react';

export default class ListRow extends React.Component {
  render() {
    return (
      <div className="list-group-item">
        <button className="btn btn-danger btn-sm btn-delete" id={this.props.item._id} onClick={this.props.onDelete} type="button" value="Delete">&times;</button>
        <span className="lead item-description" id={this.props.item._id} onClick={this.props.onUpdate}>{this.props.item.desc}</span>
      </div>
    );
  }
}
