// client-vue/src/components/List.vue
<template>
  <div class="card">
        <div class="card-header">
          List of Tasks
        </div>
        <div class="card-body">
          <p class="card-text alert alert-primary">Click on the task description to edit</p>
        </div>
        <div class="list-group" >
          <ListRow v-for="item in items" :key="item._id" v-bind:item="item" v-bind:onUpdate="updateItem" v-bind:onDelete="deleteItem"/>
        </div>
        <div class="card-body">
          <button class="btn btn-info" v-on:click="addItem">New task</button>
        </div>
      </div>
</template>

<script>
import ListRow from '@/components/ListRow.vue'
import ApiService from '@/components/ApiService.vue'

export default {
  name: 'List',
  data () {
    return {
      items: []
    }
  },
  components: {
    ListRow
  },
  created () {
    this.getItems()
  },
  methods: {
    getItems () {
      ApiService.all(items => {
        items.forEach(item => {
          item.desc = ApiService.decodeHTML(item.desc)
        })
        this.items = items
      })
    },
    addItem () {
      this.$router.push('add')
    },
    deleteItem (event) {
      const id = event.target.id
      ApiService.delete(id, () => {
        this.getItems()
      })
    },
    updateItem (event) {
      const id = event.target.id
      this.$router.push('/update/' + id)
    }
  }
}
</script>

// client-angular/src/app/list/list.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from "@angular/router";
import { Item } from '../api-service/item';
import { ApiService } from '../api-service/api.service';

@Component({
  selector: 'app-list',
  templateUrl: './list.component.html',
  styleUrls: ['./list.component.scss'],
  providers: [ApiService],
})
export class ListComponent implements OnInit {
  list: Item[];

  constructor(
    private router: Router,
    private apiService: ApiService,
  ) { }

  ngOnInit(): void {
    this.getItems();
  }

  getItems(): void {
    this.apiService.all()
      .subscribe(items => {
        items.forEach(item => {
          item.desc = (this.apiService.decodeHTML(item.desc))
        })
        return (this.list = items)
      });
  }

  addItem() {
    this.router.navigate(['/add']);
  }

  deleteItem(item): void {
    const id = item._id;
    this.apiService
      .delete(id)
      .subscribe(result => {
        this.getItems();
      })
  }

  updateItem(item): void {
    const id = item._id;
    this.router.navigate(['/update/', id]);
  }
}

<div class="card">
  <div class="card-header">
    List of Tasks
  </div>
  <div class="card-body">
    <p class="card-text alert alert-primary">Click on the task description to edit</p>
  </div>
  <div class="list-group">
    <app-list-row *ngFor="let item of list" [item]="item" (onDelete)="deleteItem(item)" (onUpdate)="updateItem(item)" class="list-group-item"></app-list-row>
  </div>
  <div class="card-body">
    <button (click)="addItem()" class="btn btn-info">New task</button>
  </div>
</div>
