// client-vue/src/components/Update.vue
<template>
  <Form
    title="Edit Task"
    v-model="item.desc"
    submitTitle="Update"
    v-bind:handleSubmit="updateItem"
  />
</template>

<script>
import Form from '@/components/Form.vue'
import ApiService from '@/components/ApiService.vue'

export default {
  name: 'Update',
  components: {
    Form
  },
  data () {
    return {
      item: ''
    }
  },
  created () {
    ApiService.get(this.$route.params.id, item => {
      this.item = item
    })
  },
  methods: {
    updateItem () {
      ApiService.update(this.item.desc, this.item._id, () => {
        this.$router.push('/')
      })
    }
  }
}
</script>

// client-angular/src/app/update/update.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from "@angular/router";
import { ActivatedRoute } from '@angular/router';

import { Item } from '../api-service/item';
import { ApiService } from '../api-service/api.service';

@Component({
  selector: 'app-update',
  templateUrl: './update.component.html',
  styleUrls: ['./update.component.scss'],
  providers: [ApiService],
})
export class UpdateComponent implements OnInit {
  item: Item
  public id: string;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private apiService: ApiService
  ) { }

  ngOnInit() {
    this.route.paramMap.subscribe(params => {
      this.id = params.get('id')
    });
    this.get(this.id)
  }

  get(id: string): void {
    this.item = undefined;

    if (id) {
      this.apiService
        .get(id)
        .subscribe(res => {
          return this.item = new Item(res.desc)
        });
    }
  }

  updateItem(): void {
    this.apiService
      .update(this.item, this.id)
      .subscribe(result => {
        this.router.navigate(['/']);
      })
  }

}

<app-form *ngIf="item"
  title="Edit Task"
  submitTitle="Update"
  [item]="item"
  (handleSubmit)="updateItem()"
>
</app-form>
