// client-angular/src/app/form/form.component.ts
import { Component, EventEmitter, OnInit, Input, Output, ElementRef, ViewChild } from '@angular/core';
import { Router } from "@angular/router";

import { Item } from '../api-service/item';

@Component({
  selector: 'app-form',
  templateUrl: './form.component.html',
  styleUrls: ['./form.component.scss']
})
export class FormComponent implements OnInit {
  @Input() title: string;
  @Input() submitTitle: string;
  @Input() item: Item;
  @Output() handleSubmit: EventEmitter<Item> = new EventEmitter<Item>();
  @ViewChild('descInput') descInput: ElementRef;
  alert: boolean

  constructor(
    private router: Router,
    private el: ElementRef
    ) {}

  ngOnInit(): void {
    this.alert = false;
  }

  ngAfterViewInit() {
    this.focusOnDesc();
  }

  submit(): void {
    if (this.item.desc.trim() === '') {
      this.alert = true;
      this.focusOnDesc();
  } else {
      this.handleSubmit.emit();
    }
  }

  closeAlert(): void {
    this.alert = false;
    this.focusOnDesc();
  }

  cancel() {
    this.router.navigate(['/']);
  }

  focusOnDesc(): void {
    this.descInput.nativeElement.focus();

  }

}

<div class="card">
  <form (ngSubmit)="submit()">
    <div class="card-header">
      <div class="panel-heading">
        {{ title }}
      </div>
    </div>
    <div class="card-body">
      <p class="card-text">
        Task description
      </p>
      <input #descInput type="text" [(ngModel)]="item.desc" class="form-control" name="desc" />
      <div class="alert alert-warning" id="desc-input-alert" role="alert" *ngIf="alert">
        Task description can&apos;t be empty
        <button type="button" class="close" aria-label="Close" (click)="closeAlert()">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
    <div class="card-body">
      <button type="submit" class="btn btn-primary">
        {{ submitTitle }}
      </button>
      <button type="button" class="btn btn-default" (click)="cancel()">
        Cancel
      </button>
    </div>
  </form>
</div>

// client-vue/src/components/Form.vue
<template>
  <div class="card">
    <form v-on:submit.prevent="submit">
      <div class="card-header">
        <div class="panel-heading">
          {{title}}
        </div>
      </div>
      <div class="card-body">
        <p class="card-text">
          Task description
        </p>
        <input
          type="text"
          class="form-control"
          v-model="descLocal"
          ref="desc"
        />
        <div v-if="alert" class="alert alert-warning" id="desc-input-alert" role="alert">
          Task description can&apos;t be empty
          <button type="button" class="close" aria-label="Close" v-on:click="closeAlert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
      <div class="card-body">
        <button
          type="submit"
          class="btn btn-primary"
        >
          {{submitTitle}}
        </button>
        <button type="button" class="btn btn-info" v-on:click="cancel">Cancel</button>
      </div>
    </form>
  </div>
</template>

<script>
export default {
  name: 'Form',
  props: {
    title: String,
    desc: String,
    submitTitle: String,
    handleSubmit: Function
  },
  model: {
    prop: 'desc',
    event: 'descChange'
  },
  computed: {
    descLocal: {
      get () {
        return this.desc
      },
      set (value) {
        this.$emit('descChange', value)
      }
    }
  },
  mounted () {
    this.focusOnDesc()
  },
  data () {
    return {
      alert: false
    }
  },
  methods: {
    submit (event) {
      if (this.descLocal.trim() === '') {
        this.alert = true
        this.focusOnDesc()
      } else {
        this.handleSubmit(this.descLocal)
      }
    },
    closeAlert () {
      this.alert = false
      this.focusOnDesc()
    },
    cancel () {
      this.$router.push('/')
    },
    focusOnDesc () {
      this.$refs.desc.focus()
    }
  }
}
</script>
