// client-angular/src/app/list-row/list-row.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-list-row',
  templateUrl: './list-row.component.html',
  styleUrls: ['./list-row.component.scss']
})
export class ListRowComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<button 
  class="btn btn-delete btn-danger bmd-btn-fab bmd-btn-fab-sm"
  [id]="item._id"
  (click)="delete()"
  type="button"
  value="Delete"
>
  &times;
</button>
<span
  class="lead item-description"
  [id]="item._id"
  [routerLink]="['/update', this.item._id]"
>
  {{ item.desc }}
</span>

// client-vue/src/components/ListRow.vue
<template>
  <div class="list-group-item">
    <button
      v-bind:id="item._id"
      class="btn btn-delete btn-danger bmd-btn-fab bmd-btn-fab-sm"
      value="Delete"
      v-on:click="onDelete"
    >
      &times;
    </button>
    <span
      v-bind:id="item._id"
      class="lead item-description"
      v-on:click="onUpdate"
    >
      {{item.desc}}
    </span>
  </div>
</template>

<script>
export default {
  name: 'ListRow',
  props: {
    item: Object,
    onDelete: Function,
    onUpdate: Function
  }
}
</script>
